kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

workspace:
  path: /drone/src

steps:
  - name: Build
    environment:
        MATCH_PASSWORD:
            from_secret: MATCH_PASSWORD
    commands:
      - echo hello
      - echo $PWD
      - whoami
      - eval "$(rbenv init -)"
      - rbenv version
      - bundle install
      - bundle exec fastlane internal
