kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

workspace:
  path: /drone/src

steps:
  - name: Prepare
    commands:
      - rbenv local 2.7.6
      - bundle exec install

  - name: Build
  
    environment:
        MATCH_PASSWORD:
            from_secret: MATCH_PASSWORD
    commands:
      - bundle exec fastlane internal

