kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

workspace:
  path: /drone/src

steps:
  - name: Build
    environment:
        MATCH_PASSWORD:
            from_secret: MATCH_PASSWORD
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
    commands:
      - echo $PWD
      - whoami
      - eval "$(rbenv init -)"
      - rbenv install 2.7.6
      - bundle install
      - security unlock-keychain -p qwertyu "/Users/ec2-user/Library/Keychains/Login.keychain-db"
      - bundle exec fastlane internal
