kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

workspace:
  path: /drone/src

steps:
  - name: Build
    environment:
        MATCH_PASSWORD:
            from_secret: MATCH_PASSWORD
        GPG_PASSWORD:
            from_secret: PWD
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
    commands:
      - echo $PWD
      - whoami
      
      - echo $GPG_PASSWORD | gpg --batch --yes --passphrase-fd 0 -d -o fastlane/api-key.json fastlane/api-key.json.gpg
      
      - security delete-keychain password "/Users/ec2-user/Library/Keychains/KCH.keychain"
      - security create-keychain -p password "/Users/ec2-user/Library/Keychains/KCH.keychain"
      - security unlock-keychain -p password "/Users/ec2-user/Library/Keychains/KCH.keychain"
      - security list-keychains
      - security add-trusted-cert -d -r unspecified -k "/Users/ec2-user/Library/Keychains/KCH.keychain" /Users/ec2-user/AppleWWDRCA.cer
      
      - eval "$(rbenv init -)"
      - rbenv install 2.7.6
      - bundle install
      
      - bundle exec fastlane internal
