kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

workspace:
  path: /drone/src

steps:
  - name: Build
    environment:
        MATCH_PASSWORD:
            from_secret: MATCH_PASSWORD
        GPG_PASSWORD:
            from_secret: PWD
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
    commands:
      - echo $PWD
      - whoami
      - eval "$(rbenv init -)"
      - rbenv install 2.7.6
      - bundle install
      - echo $GPG_PASSWORD | gpg --batch --yes --passphrase-fd 0 -d -o api-key.json api-key.json.gpg
      - bundle exec fastlane internal
