kind: pipeline
type: exec
name: default

platform:
  os: darwin
  arch: amd64

workspace:
  path: /drone/src

steps:
  - name: Build
    environment:
        MATCH_PASSWORD:
            from_secret: MATCH_PASSWORD
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
    commands:
      - echo hello
      - echo $PWD
      - whoami
      - eval "$(rbenv init -)"
      - rbenv install 2.7.6
      - bundle install
      - git clone git@github.com:Heads-and-Hands/certs-ios.git
      - bundle exec fastlane internal
